### ISSUE TITLE
TXF:  StructOpt atoms too close for VASP

### ISSUE THREAD

**Issue by cmgtam** [uw-cmg/StructOpt_modular#29] opened 2016-07-18 19:47 UTC
Transferred from uw-cmg/MAST. Close if it no longer applies.

Need to do a better job preventing atoms from being too close for VASP runs during GA defect optimization.

**Comment by jjmaldonis** [comment] 2016-07-19 23:19
Duplicate of #7

**Closed as completed by jjmaldonis** 2016-07-19 23:19 UTC
